### PR TITLE
cloudfront header support

### PR DESCRIPTION
**Pull request by slikk66**

### CODE REVIEW

**Comment by jamesmehorter** [comment]
thanks for submitting!

please update your pr to use ! empty() instead of isset() and checking true. its cleaner and easier to maintain. thanks!

**Comment by slikk66** [comment]
Thanks James!  As far as you know this is the correct method to achieve
this correct?  Created the PR for a customer of yours that says he's worked
with you in past.  He claims using this broke his AJAX loading.. but I
think might be some other caching instead causing issues.  We're setting up
a staging environment to test further.  I'll update the PR as suggested and
resubmit.

**Comment by slikk66** [comment]
Second quick comment.. I can add the !empty() test, but because the value
is likely considered a string, I'll still have to compare it I believe, see
example from php -a below:

----
php > $var = "true";
php > if ( $var ) { print "yes"; }
yes
php > $var = "false";
php > if ( $var ) { print "yes"; }



yes
----

**Comment by jamesmehorter** [comment]
hey again, yeah this is the right place. 

ok, in that case we should  use ! empty() and change the truthy comparison operator to a strict type comparison, ie === instead of ==

**Comment by jamesmehorter** [comment]
... so that its clear youre expecting a string

**Comment by slikk66** [comment]
Great -

I'll run a var_dump on the $_SERVER to confirm the variable type and use
the appropriate truth comparison be it string or boolean.

Thanks for help!

**Comment by slikk66** [comment]
Hi James, OK fixed it up and had a small battle with whitespace - but think we're good to go.  Let me know if we can get this added in for our customer to use!  Thanks -

**Comment by jamesmehorter** [comment]
Verifying that the travis build is failing due to a travis bug with PHP 5.2.x

Merging this..

**Comment by jamesmehorter** [comment]
Thanks again, @slikk66!

I've released v3.0.2 of the plugin (https://wordpress.org/plugins/device-theme-switcher/) which includes your contribution. I've also gave you a shoutout https://github.com/jamesmehorter/device-theme-switcher/wiki/5-Changelog :) 

And I've emailed Davis letting him know to update the plugin.

**Comment by slikk66** [comment]
Awesome thanks James!

**Pull request merged**
